### ISSUE TITLE
ADSBlol feed using adsb-feeder-image erroring out?

### ISSUE THREAD

**Issue by MrAirspace** [dirkhh/adsb-im-web#10]
Dear all,
I wanted to feed to ADSBlol so as per the instructions (https://www.adsb.lol/docs/hardware/adsb-equipment/) I ordered an AirNav RadarBox FlightStick and the pertaining antenna. Initially I tried the 'bare metal' command line approach but since I could not get it working I switched to the approach of using an adsb-feeder-image (https://adsb.im/howto). I followed all the steps but after the html dashboard page where I select the aggregators I want to feed to, the following page and after a couple of minutes the following html alert appears:
![what to do](https://github.com/dirkhh/adsb-im-web/assets/144953682/88ee3c02-5ab1-48c9-93b2-01d2e26ef666)

Is there any easy solution to this? I have to admit that Im unsure what it means. If for context purposes it is of any help, this is my hardware (so flight hardware as stated above, RPi is the Zero 2W. Kitchen environment only temporary location for testing - please ignore the kiwifruit)
![IMG_3601](https://github.com/dirkhh/adsb-im-web/assets/144953682/9f523cb0-e83d-4a67-93da-748c8a23cc71)

If anybody has a solution to this, please let me know, greatly appreciated :) Thanks!
Sebastiaan.

**Comment by MrAirspace** [comment]
I think it has to do with the (too limited) performance of the Pi Zero 2W, in the end I got up to this stage (see image) but soon thereafter the pi turns non-responsive and you can not even ssh into it any more. 
![screenshot2](https://github.com/dirkhh/adsb-im-web/assets/144953682/5d71306c-3ebe-4668-8097-2b0079a80984)
![screenshot1](https://github.com/dirkhh/adsb-im-web/assets/144953682/9e7e1cb8-6c5f-45b9-a921-6dc7ee0fe6df)

I think I will try with an RPi 4 in the coming days once I get it delivered. But in the meantime any feedback for the Pi Zero 2W still greatly appreciated, eager to learn more in this field :) Thanks again :)

**Comment by dirkhh** [comment]
The Pi Zero 2W is indeed at the very low end of what can work. But it should work fine, just slowly in places. 

My first guess is power issues. The OTA port that you connect the SDR to may struggle to provide enough power for an SDR with LNA like the green stick that you use. 

What kind of power supply do you use to power the Zero 2W? Powering these boards with "USB chargers" usually doesn't work. 

So my two suggestions would be
- use a powered USB hub to plug the SDR in
- make sure you have an actual USB power supply to power the Pi Zero 2W

**Comment by MrAirspace** [comment]
Sorry for the duplication, I will close this and continue on zulipchat. Thanks for the feedback and suggestions here :)

**Comment by MrAirspace** [comment]
Since maybe it is also of help to other people: it was indeed the power supply, the RPi Zero 2W official power supply delivers 5.1V, 2.5A and before I was using a charger of 5.0V 2A. After I got the official power supply, everything worked. And indeed using a better quality microSD card with also more GB storage size made the RPi operating faster too (which I read on your website https://adsb.im/faq).
Thanks again Dirk for your support :)
