### ISSUE TITLE
FAQ - "Moving to ADSB.im"

### ISSUE THREAD

**Issue by SpaceRichard** [dirkhh/adsb-im-web#11]
As I just recently move to ADSB.im I miss the following information and think it could be good to add this to the FAQ:

- Can I transfer my current feeder/station IDs to ADSB.im?
-> Yes, you can transfer the Sharing/API/Feeder Key/ID to ADSB.im during the Setup. Just note them down prior you switch your current feeder off. Currently suported: FlightAware, FlightRadar24, RadarBox, Plane.Watch, PlaneFinder, ADSBHub, OpenSky Network, RadarVirtuel, 1090MHz UK

What helps me was this guide: https://sdr-enthusiasts.gitbook.io/ads-b/feeder-containers/feeding-flightaware-piaware
and the following pages - not sure if this can be mentioned as well.

**Comment by dirkhh** [comment]
Good suggestions - except for that link... the way to get a new Piaware ID in adsb.im is way simpler. Check the checkbox, don't enter anything in the input area that appears and click the button. It will do everything for you.

**Comment by SpaceRichard** [comment]
Sure for new install. 

The link was more to get the current ID/Key in case you move to adsb.im form different installations. 
it’s nicely explained how to get the current key per service.

**Comment by dirkhh** [comment]
I guess to me it makes more sense to copy the `piaware-config -show feeder-id` into the FAQ

**Comment by dirkhh** [comment]
I added a first version of this here: https://adsb.im/faq#migrate
It would be great to document for more of the aggregators how to get the key from an existing setup...

**Comment by SpaceRichard** [comment]
they are also listed there. Just checked the menu:

FR24
`cat /etc/fr24feed.ini | grep fr24key`

RadarBox
`SSH onto your existing receiver and run the command rbfeeder --showkey --no-start
SSH onto your existing receiver and run the command grep key= /etc/rbfeeder.ini`

PlaneFinder 
`To get your share code, log into your [planefinder.net](https://planefinder.net/) account, and go to "Your Receivers". Your share code will be listed next to your existing receiver.`

**Comment by dirkhh** [comment]
perfect! thank you so much for providing these (I was going to go hunting for them this weekend)

**Comment by dirkhh** [comment]
ok, I think I completed them all - would appreciate a quick sanity check...

**Comment by SpaceRichard** [comment]
It looms good from my view.
