### ISSUE TITLE
oss-notice page not work

### ISSUE THREAD

**Issue by maniflopi** [dirkhh/adsb-im-web#9]
From my laptop/phone when I open the [Open Source Notice](https://github.com/dirkhh/adsb-im-web/blob/56fa4ab1f228de19144f06ca8915295b9d503091/web/templates/base.html#L54) my browser says: `{"detail":"Not Found"}`.

If I build the image docker on my locally environment the Open Source Notice page, works!

The only difference I identify is [here](https://github.com/dirkhh/adsb-im-web/blob/56fa4ab1f228de19144f06ca8915295b9d503091/web/templates/oss-notice.html#L2), but I'm not sure if that's the problem

**Comment by dirkhh** [comment]
thanks for pointing this out - should be fixed now.
